---
title: "IPUMS_Graph"
output: html_document
date: '2022-06-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
library(ipumsr)
source("usa_00001.R")
```

```{r}
data |> 
  select(INCTOT, EMPSTAT) |> 
  mutate(inctot = as.integer(INCTOT), 
         empstat = as.factor(EMPSTAT)) |> 
  mutate(empstat = case_when(empstat == 0 ~ "NA", 
                             empstat == 1 ~ "Employed", 
                             empstat == 2 ~ "Unemployed", 
                             empstat == 3 ~ "Not in labor force")) |> 
  mutate(inctot = na_if(inctot, 9999999)) |> 
  mutate(inctot = inctot/100000) |> 
  ggplot(aes(x = inctot, 
             y = ..scaled.., 
             fill = empstat, 
             color = empstat)) + 
  geom_density(alpha = 0.3, na.rm = TRUE) + 
  xlim(c(0,8)) + 
  scale_y_continuous(labels = scales::label_number()) + 
  scale_fill_discrete(name = "Employment Status") + 
  scale_color_discrete(name = "Employment Status") + 
  theme_economist(dkpanel = TRUE) + 
  labs(title = "2019 Income Distribution by Employment Status", 
       subtitle = NULL, 
       x = "Income: Values Scaled by 1/100000", 
       y = NULL, 
       caption = "Source: IPUMS, 2019")
```

